# Generated by Django 3.2 on 2023-07-01 03:59

from django.db import migrations, models
import django.db.models.deletion
import payment.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('identifier', models.CharField(default=payment.models.get_unique_identifier, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('total_credits', models.FloatField(default=0)),
                ('total_amount_usd', models.FloatField(default=0)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('payment_updated_on', models.DateTimeField(null=True)),
                ('transaction_data', models.TextField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
