# Generated by Django 3.2 on 2023-09-09 17:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('author_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('video_url', models.TextField(blank=True, db_index=True, default='', null=True)),
                ('user_data', models.TextField(default=None, null=True)),
            ],
            options={
                'db_table': 'training_data',
            },
        ),
    ]
