# Generated by Django 3.2 on 2023-07-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_project', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='temp_file_list',
            field=models.TextField(default=None, null=True),
        ),
    ]
