# Generated by Django 3.2 on 2023-10-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_project', '0006_default_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferencelog',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='timing',
            name='aux_frame_index',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='timing',
            name='high_threshold',
            field=models.FloatField(default=100),
        ),
    ]
