# Generated by Django 3.2 on 2023-10-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_project', '0007_log_status_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='meta_data',
            field=models.TextField(default=None, null=True),
        ),
    ]
