# Generated by Django 3.2 on 2023-11-08 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_project', '0010_shot_added_and_redundant_fields_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalfileobject',
            name='inference_log',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_project.inferencelog'),
        ),
    ]
