# Generated by Django 3.2 on 2024-02-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_project', '0012_inference_time_type_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferencelog',
            name='model_name',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='internalfileobject',
            name='shot_uuid',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
